### ISSUE TITLE
Adjust CI to work with forks

### ISSUE THREAD

**Issue by rsriniva** [RedHatQuickCourses/rhods-model#7]
https://github.com/orgs/community/discussions/25217

**Comment by crymarch** [comment]
adding a comment to see if jira automation will transition this issue to "In Progress" and assign to rsriniva

**Comment by crymarch** [comment]
adding in this comment to see if jira automation will transition issue and add you as assignee

**Comment by crymarch** [comment]
adding in this comment to see if jira automation will transition issue and add you as assignee

**Comment by crymarch** [comment]
adding a comment to see if this transitions to "In Progress" in Jira

**Comment by crymarch** [comment]
just testing to see if some jira automation works... will delete after

**Comment by crymarch** [comment]
one more test

**Comment by jramcast** [comment]
Fixed in: https://github.com/RedHatQuickCourses/rhods-model/commit/b8624fc0e4bfd46199c90cd16bac788d7f15e3a8

Tested in:
* Normal PR keeps publishing the HTML to GH pages: https://github.com/RedHatQuickCourses/rhods-model/pull/8
* PR from fork tests that HTML renders, but does not publish it to GH pages: https://github.com/RedHatQuickCourses/rhods-model/pull/9

**Comment by rsriniva** [comment]
approved test PRs. THanks Jaime. Please close this issue when fix is merged into main
